/**
 * Renders instagram/feed/posts.json into #ig-feed as a responsive grid of
 * Instagram post thumbnails linking back to Instagram.
 *
 * No API calls happen here — this only reads the static posts.json file
 * generated by sync_instagram_feed.py (run daily by
 * .github/workflows/instagram-feed-sync.yml), so no Instagram credentials
 * or tokens are ever exposed to the browser or to this codebase.
 */
(function () {
  var POSTS_URL = 'instagram/feed/posts.json';
  var POST_COUNT = 6;

  var container = document.getElementById('ig-feed');
  if (!container) return;

  container.classList.add('ig-feed');

  fetch(POSTS_URL)
    .then(function (res) {
      if (!res.ok) throw new Error('Failed to load ' + POSTS_URL + ': ' + res.status);
      return res.json();
    })
    .then(function (posts) {
      if (!Array.isArray(posts) || posts.length === 0) {
        container.innerHTML = '<p class="ig-feed-empty">No posts to show yet.</p>';
        return;
      }
      container.innerHTML = posts.slice(0, POST_COUNT).map(renderPost).join('');
    })
    .catch(function (err) {
      console.error(err);
      container.innerHTML = '<p class="ig-feed-error">Couldn\'t load the Instagram feed.</p>';
    });

  function renderPost(post) {
    var caption = escapeHtml(truncate(post.caption || '', 120));
    var isVideo = post.mediaType === 'VIDEO';
    var playIcon = isVideo
      ? '<svg class="ig-play-icon" viewBox="0 0 24 24" fill="white"><path d="M8 5v14l11-7z"/></svg>'
      : '';
    // Cache-bust by post id: the sync script reuses filenames like
    // instagram/feed/1.jpg for whichever post is newest that day, so
    // without this, browsers keep serving yesterday's cached image at
    // that URL even after the underlying file (and caption) changes.
    var imgSrc = post.imageUrl + '?v=' + encodeURIComponent(post.id || '');
    return (
      '<a class="ig-post" href="' + post.permalink + '" target="_blank" rel="noopener noreferrer" title="' + caption + '">' +
        '<img src="' + imgSrc + '" alt="' + caption + '" loading="lazy">' +
        playIcon +
      '</a>'
    );
  }

  function truncate(str, n) {
    return str.length > n ? str.slice(0, n - 1) + '…' : str;
  }

  function escapeHtml(str) {
    var div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }
})();
